spring:
  application:
    name: api-gateway

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:1221"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
