spring:
  application:
    name: api-gateway
  
  rabbitmq:
    host: 127.0.0.1
    port: 1001
    username: admin
    password: admin
    
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true